"""no_change_check

Revision ID: 1aa9f12b4f5d
Revises: b3744cbbd11c
Create Date: 2026-03-17 17:32:37.121636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa9f12b4f5d'
down_revision: Union[str, None] = 'b3744cbbd11c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
